import { Inter } from "next/font/google";
import "./globals.css";
import MainLayoutWrapper from "@/components/layout/MainLayoutWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/context/CartContext";
import ChatBot from "@/components/features/ChatBot";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "NextGen Ecommerce",
    description: "Generated by create next app",
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1.5,
    userScalable: false,
};

import { fetchFilters } from "@/lib/api";

export default async function RootLayout({
    children,
}) {
    const filters = await fetchFilters();

    return (
        <html lang="en">
            <body className={`${inter.className} overflow-x-hidden`}>
                <AuthProvider>
                    <CartProvider>
                        <MainLayoutWrapper categories={filters.categories}>
                            {children}
                        </MainLayoutWrapper>
                        <ChatBot />
                        <Toaster />
                    </CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
